AllCops:
  DisplayCopNames: true
  CacheRootDirectory: tmp
  TargetRubyVersion: 2.6
  Exclude:
    - specs/**/*
    - extras/**/*
    - vendor/**/*
    - tmp/**/*
    - node_modules/**/*
    - bin/spring
    - bin/setup
    - bin/update


Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 70

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
