AllCops:
  DisplayCopNames: true
  CacheRootDirectory: tmp
  TargetRubyVersion: 2.6
  Exclude:
    - specs/**/*
    - extras/**/*
    - vendor/**/*
    - tmp/**/*


Metrics/LineLength:
  Max: 120

MethodLength:
  Max: 35

BlockLength:
  Max: 70
