version: '3'
services:
  #app:
  #  build: .
  #  command: ["sleep", "infinity"]
  #  environment:
  #  - REDIS=redis://redis:6379/2
  #  - MONGODB_URI=mongodb://mongodb:27017/noty_dev
  #  ports:
  #  - "6789:3000"
  #  volumes:
  #  #  - .:/app:cached
  #    - rails_cache:/app/tmp/cache
  #    - bundle:/bundle
  #    - node_modules:/app/node_modules
  #    - packs:/app/public/packs
  #webpack:
  #  build: .
  #  command: ["sleep", "infinity"]
  #  environment:
  #  - REDIS=redis://redis:6379/2
  #  - MONGODB_URI=mongodb://mongodb:27017/noty_dev
  #  ports:
  #  - "6789:3000"
  #  volumes:
  #  #  - .:/app:cached
  #    - rails_cache:/app/tmp/cache
  #    - bundle:/bundle
  #    - node_modules:/app/node_modules
  #    - packs:/app/public/packs
  redis:
    image: redis
    ports:
      - "6379:6379"
  influxdb:
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8083:8083
      - 8086:8086
  mongodb:
    image: mongo
    volumes:
      - mongo:/data/db
    command:
      - mongod
      - --replSet
      - noty
    ports:
      - 27017:27017

volumes:
  mongo:
  influxdb:
  rails_cache:
  bundle:
  node_modules:
  packs:
