version: '3'
services:
  redis:
    image: redis
    ports:
      - "6380:6379"
  influxdb:
    image: influxdb
    ports:
      - "8088:8086"
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
