before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod tidy
    - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/server/main.go
  id: "server"
  binary: "gaia-server"
  ldflags:
  - -s -w -X github.com/notyim/gaia.AppVersion={{.Version}} -X github.com/notyim/gaia.BuildCommit={{.Commit}} -X github.com/notyim/gaia.BuildDate={{.Date}}

- env:
  - CGO_ENABLED=0
  main: ./cmd/client/main.go
  id: "client"
  binary: "gaia-agent"
  ldflags:
  - -s -w -X github.com/notyim/gaia.AppVersion={{.Version}} -X github.com/notyim/gaia.BuildCommit={{.Commit}} -X github.com/notyim/gaia.BuildDate={{.Date}}


archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: notyim
    name: notyim
