---
- hosts: gaia
  vars:
    - gaia_version: 0.3.3
  remote_user: root
  tasks:

  - name: cleanup log
    shell: |
      rm -rf /var/log/daemon.log.* && truncate --size 0 /var/log/daemon.log

  - name: Download gaia tar ball
    get_url:
      url: https://github.com/notyim/notyim/releases/download/{{ gaia_version }}/notyim_{{ gaia_version }}_Linux_x86_64.tar.gz
      dest: /tmp/notyim_{{ gaia_version }}_Linux_x86_64.tar.gz

  - name: ensure create directory noty
    file:
      path: /var/lib/noty
      state: directory

  - name: Extract tar ball
    unarchive:
      # This file is download per remote host, so set copy to false to not attempting copying from control machine
      copy: false
      src: /tmp/notyim_{{ gaia_version }}_Linux_x86_64.tar.gz
      dest: /var/lib/noty/

  - name: Ensure systemd file
    template:
      src: systemd.j2
      dest: /etc/systemd/system/gaia.service

  - name: Cleanup
    file:
      path: /tmp/notyim_{{ gaia_version }}_Linux_x86_64.tar.gz
      state: absent

  - name: restart gaia
    systemd:
     name: gaia
     state: restarted
     enabled: yes
     daemon_reload: yes
